name: dart validation

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  FLUTTER_VERSION: "3.41.2"

jobs:
  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        working-directory: fan_control
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter ${{env.FLUTTER_VERSION}}
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.FLUTTER_VERSION}}
          channel: "stable"

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Run Dart Analysis
        uses: invertase/github-action-dart-analyzer@main
        with:
          working-directory: fan_control 
          fatal-infos: true